from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Any, Literal, Sequence

TranscriptSource = Literal["whisper", "youtube"]


@dataclass(frozen=True)
class TranscriptSourceQuality:
    source: TranscriptSource
    segment_count: int
    token_count: int
    coverage_ratio: float
    density_ratio: float
    score: float


@dataclass(frozen=True)
class PreferredTranscript:
    source: TranscriptSource
    segments: list[dict[str, Any]]
    quality: TranscriptSourceQuality
    alternative_quality: TranscriptSourceQuality
    reason: str


def _clean_rows(rows: Sequence[dict[str, Any]]) -> list[dict[str, Any]]:
    cleaned: list[dict[str, Any]] = []
    for row in rows:
        text_value = " ".join(str(row.get("text") or "").replace("\x00", " ").split())
        start_ms = max(0, int(row.get("start_ms") or 0))
        end_ms = int(row.get("end_ms") or start_ms)
        if not text_value or end_ms <= start_ms:
            continue
        cleaned.append({**dict(row), "start_ms": start_ms, "end_ms": end_ms, "text": text_value})
    return sorted(cleaned, key=lambda row: (int(row["start_ms"]), int(row["end_ms"])))


def assess_transcript_source(
    source: TranscriptSource,
    rows: Sequence[dict[str, Any]],
    *,
    duration_ms: int,
    bucket_ms: int = 60_000,
) -> tuple[list[dict[str, Any]], TranscriptSourceQuality]:
    """Measure usable time coverage without treating duplicate captions as extra evidence."""
    if duration_ms <= 0:
        raise ValueError("duration_ms must be positive")
    if bucket_ms <= 0:
        raise ValueError("bucket_ms must be positive")

    cleaned = [row for row in _clean_rows(rows) if int(row["start_ms"]) < duration_ms]
    total_buckets = max(1, math.ceil(duration_ms / bucket_ms))
    covered: set[int] = set()
    token_count = 0
    for row in cleaned:
        start_ms = min(duration_ms - 1, int(row["start_ms"]))
        end_ms = min(duration_ms, int(row["end_ms"]))
        if end_ms <= start_ms:
            continue
        first_bucket = start_ms // bucket_ms
        last_bucket = max(first_bucket, math.ceil(end_ms / bucket_ms) - 1)
        covered.update(range(first_bucket, min(last_bucket, total_buckets - 1) + 1))
        token_count += len(str(row["text"]).split())

    coverage_ratio = min(1.0, len(covered) / total_buckets)
    # A full speech transcript usually clears 60 words/minute. Capping the
    # density contribution keeps repeated caption fragments from winning on
    # raw row or token count alone.
    expected_tokens = max(1.0, (duration_ms / 60_000) * 60.0)
    density_ratio = min(1.0, token_count / expected_tokens)
    score = (coverage_ratio * 0.85) + (density_ratio * 0.15)
    return cleaned, TranscriptSourceQuality(
        source=source,
        segment_count=len(cleaned),
        token_count=token_count,
        coverage_ratio=coverage_ratio,
        density_ratio=density_ratio,
        score=score,
    )


def select_preferred_transcript(
    whisper_rows: Sequence[dict[str, Any]],
    youtube_rows: Sequence[dict[str, Any]],
    *,
    duration_ms: int,
) -> PreferredTranscript:
    """Choose one evidence source per VOD, preferring Whisper only on near ties."""
    whisper, whisper_quality = assess_transcript_source("whisper", whisper_rows, duration_ms=duration_ms)
    youtube, youtube_quality = assess_transcript_source("youtube", youtube_rows, duration_ms=duration_ms)
    if not whisper and not youtube:
        raise ValueError("no usable transcript source was found")
    if not whisper:
        return PreferredTranscript(
            source="youtube",
            segments=youtube,
            quality=youtube_quality,
            alternative_quality=whisper_quality,
            reason="whisper_unavailable",
        )
    if not youtube:
        return PreferredTranscript(
            source="whisper",
            segments=whisper,
            quality=whisper_quality,
            alternative_quality=youtube_quality,
            reason="youtube_unavailable",
        )

    # A three-point margin is large enough to represent a meaningful coverage
    # or density improvement. Whisper wins a near tie because its timestamps
    # and optional speaker labels are generated by HasanAra's native pipeline.
    if youtube_quality.score > whisper_quality.score + 0.03:
        return PreferredTranscript(
            source="youtube",
            segments=youtube,
            quality=youtube_quality,
            alternative_quality=whisper_quality,
            reason="youtube_higher_coverage_quality",
        )
    return PreferredTranscript(
        source="whisper",
        segments=whisper,
        quality=whisper_quality,
        alternative_quality=youtube_quality,
        reason="whisper_preferred_on_quality_tie",
    )


__all__ = [
    "PreferredTranscript",
    "TranscriptSource",
    "TranscriptSourceQuality",
    "assess_transcript_source",
    "select_preferred_transcript",
]
